var creatures = [
	{
		"name":"Gladiator",
		"armor_class":16,
		"hit_points":165,
		"strength":18,
		"dexterity":15,
		"constitution":16,
		"intelligence":10,
		"wisdom":12,
		"charisma":15,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":3,
					"name":"spear",
					"attack_bonus":7,
					"damage_dice":"3d8",
					"damage_bonus":4,
					"damage_type":"piercing"
				}
			]
		}
	},
	{
		"name":"Archer",
		"armor_class":17,
		"hit_points":100,
		"strength":18,
		"dexterity":16,
		"constitution":16,
		"intelligence":12,
		"wisdom":10,
		"charisma":14,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":2,
					"name":"bow",
					"attack_bonus":7,
					"damage_dice":"1d8",
					"damage_bonus":4,
					"damage_type":"piercing"
				}
			]
		}
	},
	{
		"name":"Goblin",
		"armor_class":15,
		"hit_points":12,
		"strength":8,
		"dexterity":14,
		"constitution":10,
		"intelligence":10,
		"wisdom":8,
		"charisma":8,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":1,
					"name":"scimitar",
					"attack_bonus":4,
					"damage_dice":"1d6",
					"damage_bonus":2,
					"damage_type":"slashing"
				}
			]
		}
	},
	{
		"name":"Kobold",
		"armor_class":12,
		"hit_points":10,
		"strength":7,
		"dexterity":15,
		"constitution":9,
		"intelligence":8,
		"wisdom":7,
		"charisma":8,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":1,
					"name":"dagger",
					"attack_bonus":4,
					"damage_dice":"1d4",
					"damage_bonus":2,
					"damage_type":"piercing"
				}
			]
		}
	},
	{
		"name":"Orc",
		"armor_class":13,
		"hit_points":22,
		"strength":16,
		"dexterity":12,
		"constitution":16,
		"intelligence":7,
		"wisdom":11,
		"charisma":10,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":1,
					"name":"greataxe",
					"attack_bonus":5,
					"damage_dice":"1d12",
					"damage_bonus":3,
					"damage_type":"slashing"
				}
			]
		}
	},
	{
		"name":"Hobgoblin",
		"armor_class":18,
		"hit_points":18,
		"strength":13,
		"dexterity":12,
		"constitution":12,
		"intelligence":10,
		"wisdom":10,
		"charisma":9,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":1,
					"name":"longsword",
					"attack_bonus":3,
					"damage_dice":"1d10",
					"damage_bonus":1,
					"damage_type":"slashing"
				}
			]
		}
	},
	{
		"name":"Bandit",
		"armor_class":12,
		"hit_points":18,
		"strength":11,
		"dexterity":12,
		"constitution":12,
		"intelligence":10,
		"wisdom":10,
		"charisma":10,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":1,
					"name":"scimitar",
					"attack_bonus":3,
					"damage_dice":"1d6",
					"damage_bonus":1,
					"damage_type":"slashing"
				}
			]
		}
	},
	{
		"name":"Bandit Captain",
		"armor_class":15,
		"hit_points":100,
		"strength":15,
		"dexterity":16,
		"constitution":14,
		"intelligence":14,
		"wisdom":11,
		"charisma":14,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":2,
					"name":"scimitar",
					"attack_bonus":5,
					"damage_dice":"1d6",
					"damage_bonus":3,
					"damage_type":"slashing"
				},
				{
					"number":1,
					"name":"dagger",
					"attack_bonus":5,
					"damage_dice":"1d4",
					"damage_bonus":3,
					"damage_type":"piercing"
				}
			]
		}
	},
	{
		"name":"Berserker",
		"armor_class":13,
		"hit_points":99,
		"strength":16,
		"dexterity":12,
		"constitution":17,
		"intelligence":9,
		"wisdom":11,
		"charisma":9,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":1,
					"name":"greataxe",
					"attack_bonus":5,
					"damage_dice":"1d12",
					"damage_bonus":3,
					"damage_type":"slashing"
				}
			]
		}
	},
	{
		"name":"Knight",
		"armor_class":18,
		"hit_points":80,
		"strength":16,
		"dexterity":11,
		"constitution":14,
		"intelligence":11,
		"wisdom":11,
		"charisma":15,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":2,
					"name":"greatsword",
					"attack_bonus":5,
					"damage_dice":"2d6",
					"damage_bonus":3,
					"damage_type":"slashing"
				}
			]
		}
	},
	{
		"name":"Scout",
		"armor_class":13,
		"hit_points":27,
		"strength":11,
		"dexterity":14,
		"constitution":12,
		"intelligence":11,
		"wisdom":13,
		"charisma":11,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":2,
					"name":"longbow",
					"attack_bonus":4,
					"damage_dice":"1d8",
					"damage_bonus":2,
					"damage_type":"piercing"
				}
			]
		}
	},
	{
		"name":"Veteran",
		"armor_class":17,
		"hit_points":90,
		"strength":16,
		"dexterity":13,
		"constitution":14,
		"intelligence":10,
		"wisdom":11,
		"charisma":10,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":2,
					"name":"longbow",
					"attack_bonus":5,
					"damage_dice":"1d8",
					"damage_bonus":3,
					"damage_type":"slashing"
				},
				{
					"number":1,
					"name":"shortsword",
					"attack_bonus":5,
					"damage_dice":"1d6",
					"damage_bonus":3,
					"damage_type":"slashing"
				}
			]
		}
	},
	{
		"name":"Ogre",
		"armor_class":11,
		"hit_points":91,
		"strength":19,
		"dexterity":8,
		"constitution":16,
		"intelligence":5,
		"wisdom":7,
		"charisma":7,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":1,
					"name":"greatclub",
					"attack_bonus":6,
					"damage_dice":"2d8",
					"damage_bonus":4,
					"damage_type":"budgeoning"
				}
			]
		}
	},
	{
		"name":"Half-Ogre",
		"armor_class":12,
		"hit_points":48,
		"strength":17,
		"dexterity":10,
		"constitution":14,
		"intelligence":7,
		"wisdom":9,
		"charisma":10,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":1,
					"name":"battleaxe",
					"attack_bonus":5,
					"damage_dice":"2d10",
					"damage_bonus":3,
					"damage_type":"slashing"
				}
			]
		}
	},
	{
		"name":"Griffon",
		"armor_class":12,
		"hit_points":91,
		"strength":18,
		"dexterity":15,
		"constitution":16,
		"intelligence":2,
		"wisdom":13,
		"charisma":8,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":1,
					"name":"beak",
					"attack_bonus":6,
					"damage_dice":"1d8",
					"damage_bonus":4,
					"damage_type":"piercing"
				},
				{
					"number":1,
					"name":"claws",
					"attack_bonus":6,
					"damage_dice":"2d6",
					"damage_bonus":4,
					"damage_type":"slashing"
				}
			]
		}
	},
	{
		"name":"Hill Giant",
		"armor_class":13,
		"hit_points":160,
		"strength":21,
		"dexterity":8,
		"constitution":19,
		"intelligence":5,
		"wisdom":9,
		"charisma":6,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":2,
					"name":"greatclub",
					"attack_bonus":8,
					"damage_dice":"3d8",
					"damage_bonus":5,
					"damage_type":"bludgeoning"
				}
			]
		}
	},
	{
		"name":"Test Monk",
		"armor_class":19,
		"hit_points":58,
		"strength":11,
		"dexterity":20,
		"constitution":15,
		"intelligence":13,
		"wisdom":18,
		"charisma":13,
		"damage_resistances":["piercing", "slashing"],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":2,
					"name":"quarterstaff",
					"attack_bonus":8,
					"damage_dice":"1d8",
					"damage_bonus":5,
					"damage_type":"bludgeoning"
				},
				{
					"number":2,
					"name":"unarmed",
					"attack_bonus":8,
					"damage_dice":"1d6",
					"damage_bonus":5,
					"damage_type":"bludgeoning"
				}
			]
		}
	},
	{
		"name":"Test Barbarian",
		"armor_class":18,
		"hit_points":85,
		"strength":11,
		"dexterity":20,
		"constitution":15,
		"intelligence":13,
		"wisdom":18,
		"charisma":13,
		"damage_resistances":["acid","bludgeoning","cold","fire","force","lightning","necrotic","piercing","poison","radiant","slashing","thunder"],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":2,
					"name":"greatsword",
					"attack_bonus":12,
					"damage_dice":"2d6",
					"damage_bonus":11,
					"damage_type":"slashing",
					"great_weapon_fighting":true,
					"crit_range":20
				}
			]
		}
	},
	{
		"name":"Test Fighter",
		"armor_class":19,
		"hit_points":114,
		"strength":11,
		"dexterity":20,
		"constitution":15,
		"intelligence":13,
		"wisdom":18,
		"charisma":13,
		"damage_resistances":[],
		"damage_immunities":[],
		"actions":{
			"attack":[
				{
					"number":3,
					"name":"longsword",
					"attack_bonus":9,
					"damage_dice":["1d10", "2d6"],
					"damage_bonus":5,
					"damage_type":"slashing",
					"crit_range":19
				}
			]
		}
	},
	{
		"name":"Clay Golem",
		"armor_class":14,
		"hit_points":196,
		"strength":20,
		"dexterity":9,
		"constitution":18,
		"intelligence":3,
		"wisdom":8,
		"charisma":1,
		"damage_resistances":[],
		"damage_immunities":["acid", "poison", "psychic"],
		"actions":{
			"attack":[
				{
					"number":2,
					"name":"slam",
					"attack_bonus":8,
					"damage_dice":"2d10",
					"damage_bonus":5,
					"damage_type":"bludgeoning",
					"crit_range":20
				}
			]
		}
	},
	{
		"name":"Flesh Golem",
		"armor_class":9,
		"hit_points":198,
		"strength":19,
		"dexterity":9,
		"constitution":18,
		"intelligence":6,
		"wisdom":10,
		"charisma":5,
		"damage_resistances":[],
		"damage_immunities":["lightning", "poison"],
		"actions":{
			"attack":[
				{
					"number":2,
					"name":"slam",
					"attack_bonus":7,
					"damage_dice":"2d8",
					"damage_bonus":4,
					"damage_type":"bludgeoning",
					"crit_range":20
				}
			]
		}
	},
];